# These are supported funding model platforms

github: [chaishillomnitech1]
# patreon: # your-patreon-username
# open_collective: # your-open-collective-name
# ko_fi: # your-ko-fi-username
# tidelift: # npm/package-name
# community_bridge: # project-name
# liberapay: # your-liberapay-username
# issuehunt: # your-issuehunt-username
# otechie: # your-otechie-username
# lfx_crowdfunding: # your-lfx-crowdfunding-project-name
# polar: # your-polar-username
# buy_me_a_coffee: # your-buy-me-a-coffee-username
# thanks_dev: # your-thanks.dev-username
custom: ['https://chaistthegreat.com']
